
  - name: Add application user
    ansible.builtin.user:
      name: "{{APP_USER}}"
    when: APP_USER is defined
  - name: Download App content
    ansible.builtin.get_url:
      url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
      dest: /tmp/{{COMPONENT}}.zip
  - name: Remove prevoius App content
    ansible.builtin.file:
      path: "{{APP_LOC}}"
      state: absent
  - name: Unzip the app content
    ansible.builtin.unarchive:
      src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
      dest: /tmp
      remote_src: yes
  - name: Copy APP content inside nginx
    ansible.builtin.copy:
      src: /tmp/{{COMPONENT}}-main/
      dest: "{{APP_LOC}}"
      remote_src: yes
